### ISSUE TITLE
kudos button stops with blue border round button in Chrome

### ISSUE THREAD

**Issue by snooksnufc** [o2dazone/StravaKudos#18]
kudos button stops with blue border round button in Chrome? Is this down to strava throttling the amount of Kudos, and how do I quickly resolve without having to reload the page and scroll down all the activities? Thanks in advance.

**Comment by snooksnufc** [comment]
![image](https://user-images.githubusercontent.com/43268529/45545597-a7446680-b812-11e8-8343-a3eb6f6f60ef.png)

**Comment by o2dazone** [comment]
The blue border is just a focus state of the button. This is likely due to firing too many Kudos at one time, which Strava dislikes. We display a warning if you attempt to do more than 100 Kudos at a time, though that number is up to Strava, so they might've changed it. You can tell you've been throttled if you attempt to click "Kudos" on an activity and nothing happens. (Which means it's not related to StravaKudos at all)

**Comment by o2dazone** [comment]
hey @snooksnufc this might be the same issue as https://github.com/o2dazone/StravaKudos/issues/19

Once version 0.11 is published, let me know if it fixed it for you.
